### ISSUE TITLE
HTTPS launches always result in an invalid signature.

### ISSUE THREAD

**Issue by ryanucode** [omsmith/ims-lti#62]
We are using this library with a LTI application that interfaces with the [aNewSpring LMS](http://www.anewspring.com/). Using the same key, secret, and launch url (with the exception of http: and https:) results in the HTTP launch being valid, while the HTTPS launch is invalid.

The same result can be reproduced using the official [IMS Consumer Emulator](http://lti.tools/test/tc.php).

**Comment by omsmith** [comment]
Have you seen #55 #43 and #28? Essentially, if you're being a reverse proxy / load balancer, you should enable trusting `X-Forwarded-Proto` in your application stack.

If that's not the case, please let me know.

**Comment by SidneyNemzer** [comment]
Hello, I'm having this same issue, but `app.enable('trust proxy')` doesn't work because (for some reason?) the proxied request doesn't have the `X-Forwarded-Proto` header.

I can think of a few fixes:

1. Force the `request.protocol` to return `'https'`. No luck so for, it seems that the field is read-only
2. Add an option in this library to force a protocol, regardless of the `request.protocol`.

I'm using a Firebase function (aka Google Cloud Function) to run this, which may explain why the protocol doesn't actually reflect the protocol used by our LTI provider (aNewSpring).
